# Generated by Django 4.0.1 on 2023-10-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='opinion',
            field=models.CharField(choices=[('bardzo_dobra', 'Bardzo dobra'), ('dobra', 'Dobra'), ('przecietna', 'Przeciętna'), ('słaba', 'Słaba')], max_length=20, null=True),
        ),
    ]
