# Generated by Django 4.0.1 on 2023-10-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_book_read_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreInfoBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_info', models.CharField(choices=[('krótka', 'Krótka'), ('długa', 'Długa')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='read_book_more_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.moreinfobook'),
        ),
    ]
